# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jhyeongw <jhyeongw@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/24 21:29:58 by jhyeongw          #+#    #+#              #
#    Updated: 2024/04/24 22:08:48 by jhyeongw         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


NAME = ft_display_file

SRC = ft_display_file.c \
	  function.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) $(SRC)

clean:

fclean: clean
	rm -rf $(NAME)
